### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by leavesullic** [mit-han-lab/bevfusion#112]
I'm a new rookie to be honest, and I wonder where to modify the batch_size in this project.
I got no result after searched in the config files.
I ask this question because all my 4 V100 gpus use very little memory even I modify the 'samples_per_gpu' to 400, which is very inefficient.
![显存](https://user-images.githubusercontent.com/43094873/186307569-946df8c1-cbef-49cb-aadf-6adf657859f7.png)
Thanks for your help and looking forward to your guidance :)

**Comment by kentang-mit** [comment]
`samples_per_gpu` is the correct field to modify. However, your observation does seem abnormal to me. Perhaps you can add the `-v` flag to the `torchpack` command to see whether there are error messages.

**Comment by leavesullic** [comment]
> `samples_per_gpu` is the correct field to modify. However, your observation does seem abnormal to me. Perhaps you can add the `-v` flag to the `torchpack` command to see whether there are error messages.

Thanks a lot, I'll try

**Comment by leavesullic** [comment]
Hi Haotian,
I solved last problem by adding the -v flag, thank you very much.
However new problem came out:

Traceback (most recent call last):
  File "tools/train.py", line 96, in <module>
    main()
  File "tools/train.py", line 85, in main
    train_model(
  File "/home/yetonghui/project/mitbevfusion/mmdet3d/apis/train.py", line 93, in train_model
    cfg.lr_config,
  File "/home/yetonghui/project/tools/anaconda3/envs/mit_bevfusion/lib/python3.8/site-packages/mmcv/utils/config.py", line 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/yetonghui/project/tools/anaconda3/envs/mit_bevfusion/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'lr_config'

I checked the items in cfg but there's no key named 'lr_config'. So I wonder where to find this 'lr-config'. 
Maybe I got some omissions in the yaml files? But I git clone this project completely, which means the yaml files are completely correct.
Please point out my mistakes.

Best,
Tonghui
![1](https://user-images.githubusercontent.com/43094873/186575260-d2814eaf-8164-4526-b257-cc981fd24179.png)
![2](https://user-images.githubusercontent.com/43094873/186575274-8bfc1955-fdc0-42cd-a40b-2ccd9033525d.png)

**Comment by kentang-mit** [comment]
That's because we haven't released the `lr_config` in the current release. We anticipate that the training details will be released next month, please stay tuned.

**Comment by leavesullic** [comment]
> 

thank u :)
It is really an excellent work!

wish u the best

**Comment by kentang-mit** [comment]
Closed due to inactivity.
