### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by Deephome** [mit-han-lab/bevfusion#134]
Thank you for your great work. When I run the evaluation command `torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox`, I get the following error. Can you give me some suggestion?

`
Traceback (most recent call last):
  File "tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/home/ubuntu/code/early_fusion/bevfusion/mmdet3d/apis/__init__.py", line 2, in <module>
    from .train import *
  File "/home/ubuntu/code/early_fusion/bevfusion/mmdet3d/apis/train.py", line 15, in <module>
    from mmdet.core import DistEvalHook
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 10, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/ubuntu/anaconda3/envs/mmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
`

**Comment by Deephome** [comment]
Problem solved after I re-install mmcv-full==1.4.0
