### ISSUE TITLE
Cuda execution failed when running visualization

### ISSUE THREAD

**Issue by carlinds** [mit-han-lab/bevfusion#194]
Hi,

I'm trying to run the following vizualisation:
`torchpack dist-run -np 1 python tools/visualize.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml --checkpoint pretrained/bevfusion-det.pth --out-dir viz/fusion-det-pred --mode pred`

I'm using the provided docker image so the environment should be identical to what's described [here](https://github.com/mit-han-lab/bevfusion#prerequisites). I have also run `python setup.py develop`.

The only change I've made is to reduce the number of samples per gpu to 1 in [this config file](https://github.com/mit-han-lab/bevfusion/blob/main/configs/nuscenes/default.yaml#L261). 

However, when running the above vizualisation command I get the following error:
  
    /opt/conda/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/TensorShape.cpp:2157.)
      return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
    2022-10-18 13:51:26,375 - mmdet - INFO - load checkpoint from http path: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth
    load checkpoint from local path: pretrained/bevfusion-det.pth
      0% 0/10 [00:01<?, ?it/s]
    Traceback (most recent call last):
      File "tools/visualize.py", line 173, in <module>
        main()
      File "tools/visualize.py", line 95, in main
        outputs = model(**data)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
        output = self.module(*inputs[0], **kwargs[0])
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
        return old_func(*args, **kwargs)
      File "/home/s0001038/repos/github/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 187, in forward
        outputs = self.forward_single(
      File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
        return old_func(*args, **kwargs)
      File "/home/s0001038/repos/github/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 244, in forward_single
        feature = self.extract_lidar_features(points)
      File "/home/s0001038/repos/github/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 132, in extract_lidar_features
        x = self.encoders["lidar"]["backbone"](feats, coords, batch_size, sizes=sizes)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
        return old_func(*args, **kwargs)
      File "/home/s0001038/repos/github/bevfusion/mmdet3d/models/backbones/sparse_encoder.py", line 116, in forward
        x = self.conv_input(input_sp_tensor)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/s0001038/repos/github/bevfusion/mmdet3d/ops/spconv/modules.py", line 132, in forward
        input = module(input)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/home/s0001038/repos/github/bevfusion/mmdet3d/ops/spconv/conv.py", line 163, in forward
        outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
      File "/home/s0001038/repos/github/bevfusion/mmdet3d/ops/spconv/ops.py", line 92, in get_indice_pairs
        return get_indice_pairs_func(
    RuntimeError: mmdet3d/ops/spconv/src/indice_cuda.cu 124
    cuda execution failed with error 2
    --------------------------------------------------------------------------
    Primary job  terminated normally, but 1 process returned
    a non-zero exit code. Per user-direction, the job has been aborted.
    --------------------------------------------------------------------------
    --------------------------------------------------------------------------
    mpirun detected that one or more processes exited with non-zero status, thus causing
    the job to be terminated. The first process to do so was:
    
      Process name: [[25106,1],0]
      Exit code:    1
    --------------------------------------------------------------------------

**Comment by VeeranjaneyuluToka** [comment]
Am not sure if this is of any help, i was facing same issue with training as well. But this is not all the time. when i try multiple times, some time i use to get the above error and some times it works fine. 

Thought it might be helpful though it is not a solution. Sorry if that is not the case.

**Comment by kentang-mit** [comment]
May I ask what is the GPU you are using? You might be running OOM.

**Comment by kentang-mit** [comment]
It's slightly more than 32G for fusion models. But results can be reproduced with <32G memory if you reduce the batch size.

**Comment by yyxr75** [comment]
Hello,
I have been trained and tested this repo on nuscenes dataset and it showed no problem. So I started modifying bevfusion for my own dataset. The training step was finished perfectly and the 20th epoch trained model is saved in ./tools/run. However, when I tried to test it on my test dataset, the error popped out.

I executed `torchpack dist-run -np 1 python test.py`, the residual parse config such as model's path etc, are given default in code. I have 5 Tesla T4 GPUs with 15GB memory each, which is bigger than 12GB. Besides, I noticed that the code is error-free when training, but not in testing. The memory at the same step of code is different. Why?

>samples_per_gpu: 1
workers_per_gpu: 0

The environment of my docker container is as below: 

> absl-py                  1.3.0
addict                   2.4.0
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.2.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   5.0.1
cachetools               5.2.0
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       2.1.1
comm                     0.1.2
contourpy                1.0.6
cycler                   0.11.0
debugpy                  1.6.4
decorator                5.1.1
defusedxml               0.7.1
descartes                1.1.0
entrypoints              0.4
executing                1.2.0
fastjsonschema           2.16.2
fire                     0.5.0
flit_core                3.6.0
fonttools                4.38.0
fqdn                     1.5.1
google-auth              2.15.0
google-auth-oauthlib     0.4.6
grpcio                   1.51.1
h5py                     3.7.0
idna                     3.4
importlib-metadata       5.2.0
importlib-resources      5.10.1
ipykernel                6.19.4
ipython                  8.7.0
ipython-genutils         0.2.0
ipywidgets               8.0.4
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
jsonpointer              2.3
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           7.4.8
jupyter-console          6.4.4
jupyter_core             5.1.1
jupyter-events           0.5.0
jupyter_server           2.0.5
jupyter_server_terminals 0.4.3
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.5
kiwisolver               1.4.4
llvmlite                 0.39.1
loguru                   0.6.0
Markdown                 3.4.1
MarkupSafe               2.1.1
matplotlib               3.6.2
matplotlib-inline        0.1.6
mistune                  2.0.4
mmcv-full                1.4.0
mmdet                    2.20.0
mmdet3d                  0.0.0       /data/yyl-fusion-demo/Time_Misaligned_Camera_LiDAR_Fusion_Perception/bevfusion
mpi4py                   3.0.3
msgpack                  1.0.4
msgpack-numpy            0.4.8
multimethod              1.9.1
nbclassic                0.4.8
nbclient                 0.7.2
nbconvert                7.2.7
nbformat                 5.7.1
nest-asyncio             1.5.6
notebook                 6.5.2
notebook_shim            0.2.2
numba                    0.56.4
numpy                    1.23.5
nuscenes-devkit          1.1.9
oauthlib                 3.2.2
opencv-python            4.6.0.66
packaging                22.0
pandocfilters            1.5.0
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.3.0
pip                      22.3.1
pkgutil_resolve_name     1.3.10
platformdirs             2.6.0
prometheus-client        0.15.0
prompt-toolkit           3.0.36
protobuf                 3.20.3
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycocotools              2.0.6
pycparser                2.21
Pygments                 2.13.0
pyparsing                3.0.9
pyquaternion             0.9.9
pyrsistent               0.19.2
python-dateutil          2.8.2
python-json-logger       2.0.4
PyYAML                   6.0
pyzmq                    24.0.1
qtconsole                5.4.0
QtPy                     2.3.0
requests                 2.28.1
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rsa                      4.9
scikit-learn             1.2.0
scipy                    1.9.3
Send2Trash               1.8.0
setuptools               58.0.4
shapely                  2.0.0
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.3.2.post1
stack-data               0.6.2
tabulate                 0.9.0
tensorboard              2.11.0
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tensorpack               0.11
termcolor                2.1.1
terminado                0.17.1
terminaltables           3.1.10
threadpoolctl            3.1.0
tinycss2                 1.2.1
toml                     0.10.2
torch                    1.9.0
torchpack                0.3.1
torchvision              0.10.0
tornado                  6.2
tqdm                     4.64.1
traitlets                5.8.0
typing_extensions        4.4.0
uri-template             1.2.0
urllib3                  1.26.13
wcwidth                  0.2.5
webcolors                1.12
webencodings             0.5.1
websocket-client         1.4.2
Werkzeug                 2.2.2
wheel                    0.37.1
widgetsnbextension       4.0.5
yapf                     0.32.0
zipp                     3.11.0

Below is the error output: 

>  File "test.py", line 253, in <module>
    main()
  File "test.py", line 219, in main
    outputs = single_gpu_test(model, data_loader)
  File "/data/yyl-fusion-demo/Time_Misaligned_Camera_LiDAR_Fusion_Perception/bevfusion/mmdet3d/apis/test.py", line 12, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/yyl-fusion-demo/Time_Misaligned_Camera_LiDAR_Fusion_Perception/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 182, in forward
    feature = self.extract_lidar_features(points)
  File "/data/yyl-fusion-demo/Time_Misaligned_Camera_LiDAR_Fusion_Perception/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 125, in extract_lidar_features
    x = self.encoders["lidar"]["backbone"](feats, coords, batch_size, sizes=sizes)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/yyl-fusion-demo/Time_Misaligned_Camera_LiDAR_Fusion_Perception/bevfusion/mmdet3d/models/backbones/sparse_encoder.py", line 116, in forward
    x = self.conv_input(input_sp_tensor)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yyl-fusion-demo/Time_Misaligned_Camera_LiDAR_Fusion_Perception/bevfusion/mmdet3d/ops/spconv/modules.py", line 132, in forward
    input = module(input)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yyl-fusion-demo/Time_Misaligned_Camera_LiDAR_Fusion_Perception/bevfusion/mmdet3d/ops/spconv/conv.py", line 197, in forward
    out_features = Fsp.indice_subm_conv(
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 217, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 160, in _cast
    return type(value)(iterable)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 158, in <lambda>
    iterable = map(lambda v: _cast(v, dtype), value)
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 150, in _cast
    return value.to(dtype) if is_eligible else value
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Aborted (core dumped)

Below is the memory difference in the same code step:

in 
> 'bevfusion/mmdet3d/models/necks/generalized_lss.py'

> 
         line 96: line 101

      .......
            laterals[i] = torch.cat([laterals[i], x], dim=1)  # 2214MB GPU test/ 3074MB GPU train
            laterals[i] = self.lateral_convs[i](laterals[i])  # 11618MB GPU test/ 3074MB GPU train
            laterals[i] = self.fpn_convs[i](laterals[i])

        # build outputs
        outs = [laterals[i] for i in range(used_backbone_levels)]  # 11618MB GPU test/3114MB GPU train

        # build outputs
        outs = [laterals[i] for i in range(used_backbone_levels)]  # 11618MB GPU test/3114MB GPU train
        return tuple(outs)
