### ISSUE TITLE
bev_pool_ext.cpython-38-x86_64-linux-gnu.so: undefined

### ISSUE THREAD

**Issue by chasingw** [mit-han-lab/bevfusion#300]
use docker enviroment , but meet some error, my server has 4*2080TI GPU with driver 515.65.01
```
root@730873b34ac1:/projects/perception3d/bevfusion# torchpack dist-run -np 4 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --load_from pretrained/lidar-only-det.pth
Traceback (most recent call last):
  File "tools/train.py", line 15, in <module>
    from mmdet3d.datasets import build_dataset
  File "/projects/perception3d/bevfusion/mmdet3d/datasets/__init__.py", line 4, in <module>
    from .custom_3d import *
  File "/projects/perception3d/bevfusion/mmdet3d/datasets/custom_3d.py", line 10, in <module>
    from ..core.bbox import get_box_type
  File "/projects/perception3d/bevfusion/mmdet3d/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/projects/perception3d/bevfusion/mmdet3d/core/bbox/__init__.py", line 3, in <module>
    from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/projects/perception3d/bevfusion/mmdet3d/core/bbox/iou_calculators/__init__.py", line 1, in <module>
    from .iou3d_calculator import (
  File "/projects/perception3d/bevfusion/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 5, in
<module>
    from ..structures import get_box_type
  File "/projects/perception3d/bevfusion/mmdet3d/core/bbox/structures/__init__.py", line 1, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/projects/perception3d/bevfusion/mmdet3d/core/bbox/structures/base_box3d.py", line 5, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/projects/perception3d/bevfusion/mmdet3d/ops/__init__.py", line 23, in <module>
    from .bev_pool import *
  File "/projects/perception3d/bevfusion/mmdet3d/ops/bev_pool/__init__.py", line 1, in <module>
    from .bev_pool import bev_pool
  File "/projects/perception3d/bevfusion/mmdet3d/ops/bev_pool/bev_pool.py", line 3, in <module>
    from . import bev_pool_ext
ImportError: /projects/perception3d/bevfusion/mmdet3d/ops/bev_pool/bev_pool_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z8bev_pooliiiiiiiPKfPKiS2_S2_Pf
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[53964,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by ultrazhl98** [comment]
How do you solve this problem?
