### ISSUE TITLE
TypeError: 'DataContainer' object is not iterable

### ISSUE THREAD

**Issue by Anna1ximi** [mit-han-lab/bevfusion#488]
**When I run the command for visualization, I get this error:**

load checkpoint from local path: pretrained/bevfusion-det.pth
  0% 0/6019 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "tools/visualize.py", line 162, in <module>
    main()
  File "tools/visualize.py", line 84, in main
    outputs = model(**data)
  File "/root/miniconda3/envs/bev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/bev/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/root/autodl-tmp/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 253, in forward
    outputs = self.forward_single(
  File "/root/miniconda3/envs/bev/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/root/autodl-tmp/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 319, in forward_single
    feature = self.extract_features(points, sensor)
  File "/root/autodl-tmp/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 152, in extract_features
    feats, coords, sizes = self.voxelize(x, sensor)
  File "/root/miniconda3/envs/bev/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/bev/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/root/autodl-tmp/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 173, in voxelize
    for k, res in enumerate(points):
TypeError: 'DataContainer' object is not iterable

**Does anyone know how to fix it? Thanks very much!**

**Comment by Anna1ximi** [comment]
I just changed tools/visualize.py to single-card mode, and the rest remains unchanged. Why does this error occur? @kentang-mit 
The command I used is: torchpack dist-run -np 1 python tools/visualize.py \
	configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml \
	--checkpoint=pretrained/bevfusion-det.pth \
	--out-dir vision/pred_result \
	--mode pred \
	--bbox-score 0.2

**Comment by sym330** [comment]
I got the same error, did you fix that?

**Comment by chuliuT** [comment]
@sym330 @Anna1ximi ,use the MMDataParallel warp the model,just like this below code:
from mmcv.parallel import MMDataParallel,MMDistributedDataParallel
    # build the model and load checkpoint
    if args.mode == "pred":
        model = build_model(cfg.model)
        fp16_cfg = cfg.get("fp16", None)
        if fp16_cfg is not None:
            wrap_fp16_model(model)
        load_checkpoint(model, args.checkpoint, map_location="cpu")
        model = MMDataParallel(model, device_ids=[0])
        model.eval()

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
