### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [8, 1, 1, 1], expected input[12, 6, 256, 704] to have 1 channels, but got 6 channels instead

### ISSUE THREAD

**Issue by Simeon340703** [mit-han-lab/bevfusion#494]
Thank you for providing access to the public repository. I've been testing both the LiDAR-only detector and the BEVFusion detection model. The LiDAR-only detector is working well. However, the BEVFusion detection model is encountering an error. I haven't made any changes, so modifying the channels as mentioned in the error message could potentially impact other sections of the code. I would greatly appreciate it if you could provide an updated version or a possible solution.

2023-08-18 20:40:42,083 - mmdet3d - INFO - Homeflow: [('train', 1)], max: 6 epochs
2023-08-18 20:40:42,085 - mmdet3d - INFO - Checkpoints will be saved to /Home/sam/bevfusion/runs/run-601961a9-945d8599 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 87, in <module>
    main()
  File "tools/train.py", line 76, in main
    train_model(
  File "/Home/sam/bevfusion/mmdet3d/apis/train.py", line 126, in train_model
    runner.run(data_loaders, [("train", 1)])
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/Home/sam/bevfusion/mmdet3d/runner/epoch_based_runner.py", line 14, in train
    super().train(data_loader, **kwargs)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/Home/sam/bevfusion/mmdet3d/models/fusion_models/base.py", line 78, in train_step
    losses = self(**data)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/Home/sam/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 253, in forward
    outputs = self.forward_single(
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/Home/sam/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 301, in forward_single
    feature = self.extract_camera_features(
  File "/Home/sam/bevfusion/mmdet3d/models/fusion_models/bevfusion.py", line 133, in extract_camera_features
    x = self.encoders["camera"]["vtransform"](
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Home/sam/bevfusion/mmdet3d/models/vtransforms/depth_lss.py", line 100, in forward
    x = super().forward(*args, **kwargs)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/Home/sam/bevfusion/mmdet3d/models/vtransforms/base.py", line 349, in forward
    x = self.get_cam_feats(img, depth, mats_dict)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/Home/sam/bevfusion/mmdet3d/models/vtransforms/depth_lss.py", line 88, in get_cam_feats
    d = self.dtransform(d)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Home/sam/miniconda3/envs/Bevfusion/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
**RuntimeError: Given groups=1, weight of size [8, 1, 1, 1], expected input[12, 6, 256, 704] to have 1 channels, but got 6 channels instead**
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52671,1],0]
  Exit code:    1

**Comment by Simeon340703** [comment]
It is similar to #478
