### ISSUE TITLE
How to export a trained model to ONNX format

### ISSUE THREAD

**Issue by MaxLeo-LMZ** [mit-han-lab/bevfusion#496]
I used tool/export.py to try to export my trained model epoch_6.pth. However, the following problems are encountered:
**python tools/export.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml output/bev_
result/epoch_6.pth** 

Traceback (most recent call last):
  File "tools/export.py", line 117, in <module>
    main()
  File "tools/export.py", line 53, in main
    if isinstance(cfg.data.test, dict):
  File "/home/mingzhong/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/utils/config.py", line 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/mingzhong/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

I think I may be using an inappropriate configuration file, has anyone used tools/export.py?

Does anyone know how to export a trained model to ONNX format?

**Comment by zhijian-liu** [comment]
We currently do not support exporting the model to ONNX, but it is under consideration for future updates.
