### ISSUE TITLE
TypeError: NuScenesDataset: __init__() missing 2 required positional arguments: 'doc' and 'pos'

### ISSUE THREAD

**Issue by huzhihen** [mit-han-lab/bevfusion#500]
How can I solve this problem when I encounter it using an old version of code？

```
Traceback (most recent call last):
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/cver/zhhu/new_pycharm/bevfusion/mmdet3d/datasets/pipelines/loading.py", line 258, in __init__
    self.maps[location] = NuScenesMap(dataset_root, location)
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 92, in __init__
    self.json_obj = json.load(fh)
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/cver/zhhu/new_pycharm/bevfusion/mmdet3d/datasets/nuscenes_dataset.py", line 143, in __init__
    super().__init__(
  File "/cver/zhhu/new_pycharm/bevfusion/mmdet3d/datasets/custom_3d.py", line 69, in __init__
    self.pipeline = Compose(pipeline)
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 230, in <module>
    main()
  File "tools/test.py", line 169, in main
    dataset = build_dataset(cfg.data.test)
  File "/cver/zhhu/new_pycharm/bevfusion/mmdet3d/datasets/builder.py", line 42, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/cver/zhhu/miniconda3/envs/pytorch-bev/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: NuScenesDataset: __init__() missing 2 required positional arguments: 'doc' and 'pos'

```

**Comment by zhijian-liu** [comment]
This appears to be related to the dataset files. Could you try re-downloading the dataset to see if the issue still persists?
