### ISSUE TITLE
About creating data 

### ISSUE THREAD

**Issue by Lesliewsq** [mit-han-lab/bevfusion#548]
Everytime when I run create_data.py, this error occurs.  Have tried several times.  Always this file gets an error.
```
GT Database of NuScenesDataset
[>>>>> ] 3079/28130, 22.0 task/s, elapsed: 140s, ETA: 1140sTraceback (most recent call last):
File "tools/create_data.py", line 117, in <module>
nuscenes_data_prep(
File "tools/create_data.py", line 45, in nuscenes_data_prep
create_groundtruth_database(
File "/root/sda2/bevfusion/tools/data_converter/create_gt_database.py", line 338, in create_groundtruth_database
with open(abs_filepath, "w") as f:
OSError: [Errno 5] Input/output error: './data/nuscenes/nuscenes_gt_database/036bf10fbf124e378b7982f53f4fec43_pedestrian_0.bin'
```

**Comment by zhijian-liu** [comment]
This doesn't appear to be related to our repository; instead, it seems to be related to the file system.
