### ISSUE TITLE
run the torchpack command and error

### ISSUE THREAD

**Issue by Lawrence-Cheung** [mit-han-lab/bevfusion#610]
I followed the tutorial, and run the command:
torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox

but the error happened:
Traceback (most recent call last):
  File "C:\Users\18369\.conda\envs\bevfusion\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\18369\.conda\envs\bevfusion\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\18369\.conda\envs\bevfusion\Scripts\torchpack.exe\__main__.py", line 7, in <module>
  File "C:\Users\18369\.conda\envs\bevfusion\lib\site-packages\torchpack\launch\main.py", line 17, in main
    drunner.main()
  File "C:\Users\18369\.conda\envs\bevfusion\lib\site-packages\torchpack\launch\launchers\drunner.py", line 104, in main
    os.execve('/bin/sh', ['/bin/sh', '-c', command], environ)
FileNotFoundError: [Errno 2] No such file or directory: '/bin/sh'

I'm a new leaner so I can't figure out what's the problem, who can help?

**Comment by zhijian-liu** [comment]
We do not support running on Windows. Please run this in a Linux environment instead.
