### ISSUE TITLE
KeyError: 'radar'

### ISSUE THREAD

**Issue by F0sakens3-1415** [mit-han-lab/bevfusion#628]
### I got this error when i training ‘torchpack dist-run -np 1 python tools/train.py configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/default.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth’ 
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bevfusion/mmdet3d/datasets/dataset_wrappers.py", line 68, in __getitem__
    return self.dataset[ori_idx]
  File "/home/bevfusion/mmdet3d/datasets/custom_3d.py", line 293, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/bevfusion/mmdet3d/datasets/custom_3d.py", line 164, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/bevfusion/mmdet3d/datasets/pipelines/loading.py", line 728, in __call__
    radars_dict = results['radar']
KeyError: 'radar'

**Comment by thiesymon** [comment]
-> https://github.com/mit-han-lab/bevfusion/issues/517
